# Generated by Django 5.0 on 2024-01-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registerUser',
        ),
    ]
